#!/usr/bin/env python
# encoding: utf-8
"""
Copyright (c) 2012 Ulf Urdén.
All rights reserved.

Redistribution and use in source and binary forms are permitted
provided that the above copyright notice and this paragraph are
duplicated in all such forms and that any documentation,
advertising materials, and other materials related to such
distribution and use acknowledge that the software was developed
by the organization. The name of the
University may not be used to endorse or promote products derived
from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
"""

import sys
import urllib
from time import sleep
from xml.dom.minidom import *

tracking_no = sys.argv[1]
last_id = None

while True:
    sleep(60*5)

    try:
      fp = urllib.urlopen("http://server.logistik.posten.se/servlet/PacTrack?kolliid=%s" % (tracking_no))
      data = fp.read()
      fp.close()
    except:
      sys.exit(-1)

    if data:
      dom = parseString(data)

      def getval(node):
        return dom.getElementsByTagName("event")[-1].getElementsByTagName(node)[0].firstChild.nodeValue

      id = getval("id")
      desc = getval("description")
      where = getval("location")

      if last_id != None and id != last_id:
          print "-" * 10 + "Parcel moved!" + "-" * 10
      last_id = id
      print id, desc, where
